name: Add new issues to Project

on:
  issues:
    types: [opened]
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add to org project
        uses: actions/add-to-project@v0.6.0
        with:
          project-url: ${{ vars.PROJECT_URL }}
          github-token: ${{ secrets.PROJECTS_TOKEN }}
